version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: kampai
      POSTGRES_USER: kampai_user
      POSTGRES_PASSWORD: kampai_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
