spring:
  datasource:
    url: jdbc:postgresql://db:5432/kampai
    username: kampai_user
    password: kampai_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
